const ACTION = {
  SET_DETAIL_REQUESTED: 'SET_DETAIL_REQUESTED',
  SET_DETAIL_PAGE: 'SET_DETAIL_PAGE',
  SET_VISIBILITY: 'SET_VISIBILITY',
  SET_LIST_HOME_PAGE: 'SET_LIST_HOME_PAGE',
  SET_LIST_REQUESTED: 'SET_LIST_REQUESTED',
};

export default ACTION;
